url: https://ammarfaisal.me
baseurl: ""
title: "0xz4h1d" # the name of your site, e.g. ACME Corp.
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: aqua
repository: "ammarbinfaisal/blog"
logo: "/assets/img.jpg"

plugins:
  - jekyll-seo-tag

author:
  name     : "Ammar Faisal"
  avatar   : "/assets/img.jpg"
  bio      : "developer, security enthusiast, and a student"
  location : "New Delhi, India"

social:
  type:  # Person or Organization (defaults to Person)
  name:  # If the user or organization name differs from the site's name
  links:
    - "https://twitter.com/0xz4h1d"
    - "https://github.com/ammarbinfaisal"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/mmistakes"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mmistakes"

twitter:
  username: ammar
  card: summary

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: posts
      toc: true
      toc_sticky: true
      classes: wide
      show_date: false
      author_profile: true
      related: true
    # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes: wide