url: https://ammarfaisal.me
baseurl: ""
title: "0xz4h1d" # the name of your site, e.g. ACME Corp.
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: aqua
repository: "ammarbinfaisal/blog"
logo: "/assets/img.jpg"
search: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: posts
      toc: true
      toc_sticky: true
      classes: wide
      show_date: false
    # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes: wide

